#!/usr/bin/env python3
"""Regenerate a self-contained coordination/board.html from the mailbox .md files.

Run after every step:  python coordination/render_board.py

- No third-party deps, no server, no model -> deterministic (safe per the
  determinism invariant; this is a dev/coordination tool, not the number path).
- Output is a single self-contained HTML file you open with a double-click.
"""
import os, subprocess, html, datetime

BASE = os.path.dirname(os.path.abspath(__file__))

def read(name):
    p = os.path.join(BASE, name)
    try:
        with open(p, encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return ""

def parse_state():
    d = {}
    for line in read("STATE.md").splitlines():
        if line.startswith("#") or ":" not in line:
            continue
        k, _, v = line.partition(":")
        d[k.strip().lower()] = v.strip()
    return d

def git_last_commit():
    try:
        return subprocess.check_output(
            ["git", "-C", BASE, "log", "-1", "--pretty=%s"],
            stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return ""

S = parse_state()
commit = S.get("last_commit", "").strip()
if not commit or commit.startswith("("):
    commit = git_last_commit() or commit or "(none yet)"

inbox     = read("INBOX.md")
outbox    = read("OUTBOX.md")
questions = read("QUESTIONS.md")
gate      = read("GATE.md")
journal   = "\n".join(read("journal.md").splitlines()[-8:])
q_empty   = (not questions.strip()) or ("(empty" in questions.lower())
now       = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

def esc(t):
    return html.escape(t or "")

def strip_header(t):
    # drop a leading "# ..." title line for cleaner cards
    lines = t.splitlines()
    if lines and lines[0].lstrip().startswith("#"):
        lines = lines[1:]
    return "\n".join(lines).strip()

TPL = """<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>180Climate - Coordination Board</title><style>
:root{--bg:#0f1713;--panel:#15211b;--panel2:#1b2c23;--line:#2a4034;--ink:#e8f3ec;
--muted:#8fae9c;--accent:#39d98a;--accent2:#7cc4ff;--ok:#39d98a;--warn:#ffb454;}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);
font:15px/1.5 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif}
header{display:flex;align-items:center;gap:14px;padding:18px 22px;border-bottom:1px solid var(--line);
background:linear-gradient(180deg,#16241c,#0f1713)}.logo{width:30px;height:30px;border-radius:8px;
background:radial-gradient(circle at 30% 30%,var(--accent),#0c8a55);box-shadow:0 0 18px rgba(57,217,138,.5)}
h1{font-size:18px;margin:0}h1 small{color:var(--muted);font-weight:400;font-size:13px;display:block;margin-top:2px}
.badge{margin-left:auto;font-size:12px;color:var(--muted);display:flex;align-items:center;gap:8px}
.dot{width:9px;height:9px;border-radius:50%;background:var(--ok);box-shadow:0 0 10px var(--ok)}
.strip{display:flex;flex-wrap:wrap;gap:10px;padding:16px 22px}
.pill{flex:1;min-width:170px;background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:12px 14px}
.pill .k{font-size:11px;text-transform:uppercase;letter-spacing:.8px;color:var(--muted)}
.pill .v{font-size:16px;font-weight:600;margin-top:3px}.pill .v.run{color:var(--accent)}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:14px;padding:8px 22px 22px}
.card{background:var(--panel);border:1px solid var(--line);border-radius:14px;overflow:hidden}
.card.alert{border-color:#5a4420}.card h2{margin:0;font-size:12px;letter-spacing:1px;text-transform:uppercase;
color:var(--muted);padding:12px 15px;border-bottom:1px solid var(--line);background:var(--panel2)}
.card.alert h2{color:var(--warn)}.body{padding:14px 15px}
pre{white-space:pre-wrap;word-break:break-word;margin:0;font:12.5px/1.5 ui-monospace,Menlo,monospace;color:#cfe6d8}
.empty{color:var(--ok);font-style:italic}footer{padding:14px 22px;color:var(--muted);font-size:12px;border-top:1px solid var(--line)}
.tag{display:inline-block;font-size:11px;padding:2px 8px;border-radius:6px;background:#10331f;color:var(--accent);
border:1px solid #1d5a37;margin:2px 4px 2px 0}</style></head><body>
<header><div class="logo"></div><h1>180Climate - Coordination Board
<small>regenerated by render_board.py - the mailbox Cowork &amp; VS Code talk through</small></h1>
<div class="badge"><span class="dot"></span><span>updated __NOW__</span></div></header>
<div class="strip">
<div class="pill"><div class="k">Phase</div><div class="v">__PHASE__</div></div>
<div class="pill"><div class="k">Active Work Order</div><div class="v">__WO__</div></div>
<div class="pill"><div class="k">Status</div><div class="v run">__STATUS__</div></div>
<div class="pill"><div class="k">Last commit</div><div class="v" style="font-size:14px">__COMMIT__</div></div></div>
<div class="grid">
<div class="card"><h2>Inbox - the task now (Cowork)</h2><div class="body"><pre>__INBOX__</pre></div></div>
<div class="card"><h2>Outbox - last result (VS Code)</h2><div class="body"><pre>__OUTBOX__</pre></div></div>
<div class="card alert"><h2>Questions / blockers</h2><div class="body">__QUESTIONS__</div></div>
<div class="card"><h2>Gate (John + advisor)</h2><div class="body"><pre>__GATE__</pre></div></div>
<div class="card"><h2>Journal - recent (feeds Dreaming)</h2><div class="body"><pre>__JOURNAL__</pre></div></div></div>
<footer><b>Who writes what:</b>
<span class="tag">Cowork &rarr; INBOX, plan, board</span>
<span class="tag">VS Code &rarr; STATE/OUTBOX/evidence/journal + commits</span>
<span class="tag">John &rarr; gate decisions</span>
&nbsp; Two signals pull a human: QUESTIONS non-empty, or GATE READY.</footer></body></html>"""

q_html = '<span class="empty">&#10003; empty - no human turn needed</span>' if q_empty else "<pre>%s</pre>" % esc(strip_header(questions))

out = (TPL
    .replace("__NOW__", esc(now))
    .replace("__PHASE__", esc(S.get("phase", "P0")))
    .replace("__WO__", esc(S.get("active_wo", "(none)")))
    .replace("__STATUS__", esc(S.get("status", "SEEDED")))
    .replace("__COMMIT__", esc(commit))
    .replace("__INBOX__", esc(strip_header(inbox)) or "(empty)")
    .replace("__OUTBOX__", esc(strip_header(outbox)) or "(empty)")
    .replace("__QUESTIONS__", q_html)
    .replace("__GATE__", esc(strip_header(gate)) or "(no gate)")
    .replace("__JOURNAL__", esc(journal) or "(empty)"))

with open(os.path.join(BASE, "board.html"), "w", encoding="utf-8") as f:
    f.write(out)
print("board.html regenerated", now)
